# Generated by Django 3.1 on 2020-08-29 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_taskboard_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='column',
        ),
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_manager.taskboard'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.IntegerField(choices=[(1, '1: Idea'), (2, '2: Task'), (3, '3: In Progress'), (4, '4: Comleted')], default=1),
        ),
        migrations.DeleteModel(
            name='TaskColumn',
        ),
    ]
