# Generated by Django 3.1 on 2020-09-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_auto_20200829_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskboard',
            name='task_count',
            field=models.IntegerField(default=0),
        ),
    ]
