# Generated by Django 3.1 on 2020-09-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_taskboard_task_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bg',
            field=models.CharField(choices=[('bg1', 'Red'), ('bg2', 'Green'), ('bg3', 'Orange'), ('bg4', 'Lilac'), ('bg5', 'Blue')], default='bg5', max_length=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='stage',
            field=models.IntegerField(choices=[(1, 'Idea'), (2, 'Task'), (3, 'In Progress'), (4, 'Comleted')], default=1),
        ),
    ]
